"""add image fields to complaints

Revision ID: 10e1e4241804
Revises: 2c6fe1da5f55
Create Date: 2026-03-02 11:03:53.039648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e1e4241804'
down_revision: Union[str, Sequence[str], None] = '2c6fe1da5f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('image_path', sa.String(length=512), nullable=True))
    op.add_column('complaints', sa.Column('image_original_name', sa.String(length=255), nullable=True))
    op.add_column('complaints', sa.Column('image_gps_lat', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('image_gps_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'image_gps_lng')
    op.drop_column('complaints', 'image_gps_lat')
    op.drop_column('complaints', 'image_original_name')
    op.drop_column('complaints', 'image_path')
    # ### end Alembic commands ###
