"""add convo sessions and citizen feedback tables

Revision ID: 2c6fe1da5f55
Revises: f0f9a55f9301
Create Date: 2026-02-28 15:12:10.773525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6fe1da5f55'
down_revision: Union[str, Sequence[str], None] = 'f0f9a55f9301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=15), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_feedback_ticket_id'), 'citizen_feedback', ['ticket_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.Column('extracted_data', sa.Text(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('ticket_id', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_session_id'), 'conversation_sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_sessions_session_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_citizen_feedback_ticket_id'), table_name='citizen_feedback')
    op.drop_table('citizen_feedback')
    # ### end Alembic commands ###
