"""initial complaints table

Revision ID: f0f9a55f9301
Revises: 
Create Date: 2026-02-28 12:11:59.055363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f9a55f9301'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=15), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('roads', 'water', 'electricity', 'sanitation', 'street_lights', 'safety', 'parks', 'other', name='complaintcategory', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='complaintpriority', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'assigned', 'in_progress', 'resolved', 'rejected', name='complaintstatus', native_enum=False), nullable=False),
    sa.Column('ward', sa.String(length=120), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_ticket_id'), 'complaints', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_ticket_id'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
