"""add new complaint fields

Revision ID: f28b89ef0539
Revises: 19ad0f3b2c36
Create Date: 2026-03-04 16:45:07.582449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28b89ef0539'
down_revision: Union[str, Sequence[str], None] = '19ad0f3b2c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('current_escalation_level', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('complaints', sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'complaints', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'sla_deadline')
    op.drop_column('complaints', 'current_escalation_level')
    op.drop_column('complaints', 'risk_score')
    op.drop_column('complaints', 'department_id')
    # ### end Alembic commands ###
